Replace java based self-signed certificate generation with OpenSSL
neo4j/docs-ops-manager pull request #147
Opened 2023-09-06 10:56 UTC by alexnb

Replace java based self-signed certificate generation with instruction on how to use OpenSSL.

----

If you open a PR that needs to go into a current version, you need to *cherry-pick your commit from dev over to the current version branch*. Only then will the proper builds that generate html/pdf be run. But beware: Docs will be generated but not published automatically!

- [X] N/A - or - I have added the appropriate "cherry-pick-to" labels to this PR so I don't forget to do this later!

2023-09-06 10:58 UTC, neo-technology-commit-status-publisher commented
This PR includes documentation updates.

You can view the updated docs at https://neo4j-docs-ops-manager-147.surge.sh
<!-- Sticky Pull Request Comment -->

2023-09-19 14:20 UTC, alexnb commented
This is the first part of my documentation changes. Changes related to "Docker first look" will be in a separate PR.

2023-09-21 09:52 UTC, SaschaPeukert requested changes

2023-09-21 09:52 UTC, SaschaPeukert commented on modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
> +In order to generate a self-signed certificate for the above example, execute the following command:
Should this file not be removed or changed to: We don't do ssc anymore please see. other page.. ?

2023-09-21 10:08 UTC, alexnb commented on modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
> +In order to generate a self-signed certificate for the above example, execute the following command:
Our `ssc` tool in the _agent_ is still available. It doesn't use weak algorithms. As I spoke with Sebastian, we decided to keep it.

It is also used in our build process and I didn't want to invest too much time to replace it with `openssl` there too.

OK or do you think we should wipe it too?

2023-09-21 12:46 UTC, SaschaPeukert commented on modules/ROOT/pages/addition/agent-installation/agent-self-signed-certificates.adoc
> +In order to generate a self-signed certificate for the above example, execute the following command:
Okay, thanks for pointing that out. I could see how that might be confusing to our users but for now I am happy with you keeping it then

2023-09-21 12:46 UTC, SaschaPeukert approved these changes

2023-09-25 10:44 UTC, AlexicaWright reviewed
Some editorial comments.

2023-09-25 10:44 UTC, AlexicaWright commented on modules/ROOT/pages/first-look/docker-first-look.adoc
> +. Change to *`~/.nom/ssc`* and generate self-signed certificates as described *xref:installation/self-signed-certificate.adoc[here]*, using `server` as common name (CN) and DNS name and `127.0.0.1` a
```suggestion
. Change to *`~/.nom/ssc`* and generate self-signed certificates as described *xref:installation/self-signed-certificate.adoc[here]*, using `server` as common name (CN) and DNS name, and `127.0.0.1` as IP address.
```

2023-09-25 10:44 UTC, AlexicaWright commented on modules/ROOT/pages/first-look/docker-first-look.adoc
> +This will result in `server.cer` and `server.pfx` being created.
```suggestion
This results in the creation of `server.cer` and `server.pfx`.
```

2023-09-25 10:44 UTC, AlexicaWright commented on modules/ROOT/pages/installation/self-signed-certificate.adoc
> +Compatible self-signed certificates, generated using other libraries or online tools will also work with NOM.
```suggestion
Compatible self-signed certificates, generated using other libraries or online tools also work with NOM.
```

2023-09-25 12:16 UTC, merged